"""
Settings for stapel-cdn, resolved through ``stapel_core.conf.AppSettings``.

Configure via a ``STAPEL_CDN`` dict in Django settings::

    STAPEL_CDN = {
        "VARIANT_SIZES": [16, 32, 64, 120, 160, 240, 480, 720, 1080],
        "MAX_IMAGE_SIZE": 20 * 1024 * 1024,
    }

Resolution order per key: ``settings.STAPEL_CDN`` dict → legacy flat
``CDN_*`` setting (see ``LEGACY_ALIASES``) → flat Django setting of the
same name → environment variable → built-in default. All defaults match
the previously hardcoded values, so with no overrides behavior is
unchanged.
"""
from stapel_core.conf import AppSettings

#: Image type choices: (value, label) pairs. Mirrors the historical
#: ``ImageType`` TextChoices on the model.
DEFAULT_IMAGE_TYPES = (
    ("product", "Product"),
    ("avatar", "Avatar"),
)

#: Variant heights generated by the processing pipeline. Sizes <= 120 are
#: treated as thumbnails (high-priority, no watermark), larger ones as
#: previews. Matches the historical THUMBNAIL_SIZES + PREVIEW_SIZES.
DEFAULT_VARIANT_SIZES = (16, 32, 64, 120, 160, 240, 480, 720, 1080)

DEFAULTS = {
    "IMAGE_TYPES": DEFAULT_IMAGE_TYPES,
    "VARIANT_SIZES": DEFAULT_VARIANT_SIZES,
    # Upload size cap for images (bytes) — 20 MB.
    "MAX_IMAGE_SIZE": 20 * 1024 * 1024,
    "ALLOWED_IMAGE_EXTENSIONS": (
        ".jpg", ".jpeg", ".png", ".gif", ".webp", ".bmp", ".heic", ".heif",
    ),
    # Decompression-bomb cap: Pillow raises DecompressionBombError above
    # 2x this pixel count.
    "MAX_IMAGE_PIXELS": 50_000_000,
    # Watermark engine: dotted path to (or directly a) callable
    # ``(pyvips.Image) -> pyvips.Image`` applied to preview variants.
    # Empty (the default) disables watermarking entirely. The built-in
    # reference engine is "stapel_cdn.watermarks.text_watermark", which
    # renders WATERMARK_TEXT in the bottom-right corner; host projects
    # supply their own callable for designed watermarks.
    "WATERMARK": "",
    "WATERMARK_TEXT": "",
}

_UNSET = object()


class CdnAppSettings(AppSettings):
    """AppSettings that also honors the legacy flat ``CDN_*`` names."""

    LEGACY_ALIASES = {
        "MAX_IMAGE_SIZE": "CDN_MAX_IMAGE_SIZE",
        "ALLOWED_IMAGE_EXTENSIONS": "CDN_ALLOWED_IMAGE_EXTENSIONS",
        "MAX_IMAGE_PIXELS": "CDN_MAX_IMAGE_PIXELS",
        "WATERMARK": "CDN_WATERMARK",
        "WATERMARK_TEXT": "CDN_WATERMARK_TEXT",
    }

    def _connect_reload(self):
        try:
            from django.test.signals import setting_changed

            def _reload(*, setting, **kwargs):
                if (
                    setting == self.namespace
                    or setting in self.defaults
                    or setting in self.LEGACY_ALIASES.values()
                ):
                    self.reload()

            setting_changed.connect(_reload, weak=False)
        except Exception:  # pragma: no cover — Django not ready
            pass

    def _raw(self, key):
        from django.conf import settings

        overrides = getattr(settings, self.namespace, None) or {}
        if key not in overrides:
            legacy = self.LEGACY_ALIASES.get(key)
            if legacy is not None:
                value = getattr(settings, legacy, _UNSET)
                if value is not _UNSET:
                    return value
        return super()._raw(key)


cdn_settings = CdnAppSettings(
    "STAPEL_CDN", defaults=DEFAULTS, import_strings=("WATERMARK",)
)

__all__ = [
    "cdn_settings",
    "CdnAppSettings",
    "DEFAULTS",
    "DEFAULT_IMAGE_TYPES",
    "DEFAULT_VARIANT_SIZES",
]
