"""`docs/capabilities.json` must not drift away from the package it describes.

Every other module in the fleet emits this file from a generator
(`_capabilities.py`, a shim over `stapel_tools.capabilities`, wired into
`make contract` and gated by `make contract-check`). stapel-cdn still
hand-authors `provides`/`axes`/`extension_points`/`requires` in
capabilities.json specifically — a full generator for that document is
tracked separately — but `module`/`version` and the `surface` section ARE
now regenerated by `stapel_tools.surface --patch` (see
tests/test_capabilities_surface.py), specifically so the version field can't
rot again.

This module DOES now emit the contract TRIAD proper — docs/{schema,flows,
errors}.json, via ``stapel_cdn._codegen`` (A1, darom-storefront-design.md
§1.8/§3.10) — see tests/test_contract.py for that gate. It is
``docs/capabilities.json`` alone that stays hand-authored beyond
module/version/surface.

It had already stopped once: 0.8.1 shipped with the file still claiming
0.8.0. That is the same defect stapel-profiles 0.7.2 was released to fix,
recurring here for want of the gate rather than for want of the knowledge —
this test pins the part that provably drifted; the surface gate now pins the
rest of what `--patch` derives.
"""
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def _pyproject_version() -> str:
    text = (REPO / "pyproject.toml").read_text(encoding="utf-8")
    match = re.search(r'^version\s*=\s*"([^"]+)"', text, re.M)
    assert match, "pyproject.toml has no version"
    return match.group(1)


def test_capabilities_version_matches_the_package():
    manifest = json.loads((REPO / "docs" / "capabilities.json").read_text("utf-8"))
    assert manifest["version"] == _pyproject_version(), (
        "docs/capabilities.json is hand-authored in this module — bump it in "
        "the same commit as pyproject.toml (0.8.1 shipped claiming 0.8.0)."
    )


def test_capabilities_names_this_module():
    manifest = json.loads((REPO / "docs" / "capabilities.json").read_text("utf-8"))
    assert manifest["module"] == "stapel-cdn"
