# Generated by Django 5.2.15 on 2026-07-02 01:41

import django.db.models.deletion
import stapel_cdn.models
import stapel_cdn.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the original file', max_length=64, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=10)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('original', models.FileField(help_text='Original uploaded file', max_length=500, storage=stapel_cdn.storage.OverwriteStorage(), upload_to=stapel_cdn.models.file_upload_path)),
                ('original_size', models.BigIntegerField(help_text='File size in bytes')),
                ('refs', models.JSONField(blank=True, default=list, help_text='List of references: service/entity_type/entity_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'db_table': 'cdn_file',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_hash'], name='cdn_file_file_ha_b16a9c_idx'), models.Index(fields=['created_at'], name='cdn_file_created_ebd8b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the original file', max_length=64)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=10)),
                ('type', models.CharField(choices=stapel_cdn.models.get_image_type_choices, default='product', help_text='Type of image: product or avatar', max_length=10)),
                ('original', models.FileField(help_text='Original uploaded image', max_length=500, storage=stapel_cdn.storage.OverwriteStorage(), upload_to=stapel_cdn.models.image_upload_path)),
                ('original_width', models.IntegerField(default=0)),
                ('original_height', models.IntegerField(default=0)),
                ('original_size', models.BigIntegerField(help_text='File size in bytes')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether variants have been generated')),
                ('processing_log', models.TextField(blank=True, default='', help_text='Log of processing operations')),
                ('refs', models.JSONField(blank=True, default=list, help_text='List of references: service/entity_type/entity_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'cdn_image',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_hash'], name='cdn_image_file_ha_dfe84b_idx'), models.Index(fields=['created_at'], name='cdn_image_created_65eade_idx'), models.Index(fields=['is_processed'], name='cdn_image_is_proc_4722cb_idx')],
                'constraints': [models.UniqueConstraint(fields=('file_hash', 'type'), name='cdn_image_hash_type_unique')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the original file', max_length=64, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=10)),
                ('original', models.FileField(help_text='Original uploaded video', upload_to=stapel_cdn.models.video_upload_path)),
                ('original_width', models.IntegerField(blank=True, null=True)),
                ('original_height', models.IntegerField(blank=True, null=True)),
                ('original_size', models.BigIntegerField(help_text='File size in bytes')),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('variant_16', models.FileField(blank=True, help_text='16px height variant (no watermark)', null=True, upload_to=stapel_cdn.models.video_upload_path)),
                ('variant_32', models.FileField(blank=True, help_text='32px height variant (no watermark)', null=True, upload_to=stapel_cdn.models.video_upload_path)),
                ('variant_64', models.FileField(blank=True, help_text='64px height variant (no watermark)', null=True, upload_to=stapel_cdn.models.video_upload_path)),
                ('variant_160', models.FileField(blank=True, help_text='160px height variant with watermark', null=True, upload_to=stapel_cdn.models.video_upload_path)),
                ('variant_240', models.FileField(blank=True, help_text='240px height variant with watermark', null=True, upload_to=stapel_cdn.models.video_upload_path)),
                ('variant_480', models.FileField(blank=True, help_text='480px height variant with watermark', null=True, upload_to=stapel_cdn.models.video_upload_path)),
                ('variant_720', models.FileField(blank=True, help_text='720px height variant with watermark', null=True, upload_to=stapel_cdn.models.video_upload_path)),
                ('variant_720_jpg', models.FileField(blank=True, help_text='720px height variant (legacy compatibility)', null=True, upload_to=stapel_cdn.models.video_upload_path)),
                ('variant_1080', models.FileField(blank=True, help_text='1080px height variant with watermark', null=True, upload_to=stapel_cdn.models.video_upload_path)),
                ('variant_1440', models.FileField(blank=True, help_text='1440px height variant with watermark', null=True, upload_to=stapel_cdn.models.video_upload_path)),
                ('variant_2160', models.FileField(blank=True, help_text='2160px height variant with watermark', null=True, upload_to=stapel_cdn.models.video_upload_path)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether variants have been generated')),
                ('refs', models.JSONField(blank=True, default=list, help_text='List of references: service/entity_type/entity_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'cdn_video',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_hash'], name='cdn_video_file_ha_10f820_idx'), models.Index(fields=['created_at'], name='cdn_video_created_42f7e9_idx'), models.Index(fields=['is_processed'], name='cdn_video_is_proc_ab1356_idx')],
            },
        ),
    ]
