# cdn-modularity.md §2/§7.2: Image.type help_text now points at
# STAPEL_CDN["ASSET_TYPES"] (the client/server-shared config key, replacing
# IMAGE_TYPES) — text-only, no data change. New Audio model ("recordings"
# submodule): passthrough storage, always available; ffmpeg-audio
# compression is a separate, unimplemented opt-in (is_compressed stays
# False until a real pipeline lands).
#
# Generated by Django 6.0.7 on 2026-07-17 04:30

import django.db.models.deletion
import stapel_cdn.models
import stapel_cdn.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0003_remove_video_variant_720_jpg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=stapel_cdn.models.get_image_type_choices, default='product', help_text="Image type — validated against STAPEL_CDN['ASSET_TYPES'] (default ('avatar',); the historical 'product' default value here is only in scope for host projects that still add it).", max_length=10),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the original file', max_length=64, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_extension', models.CharField(max_length=10)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('original', models.FileField(help_text='Original uploaded audio recording (always stored as-is)', max_length=500, storage=stapel_cdn.storage.OverwriteStorage(), upload_to=stapel_cdn.models.audio_upload_path)),
                ('original_size', models.BigIntegerField(help_text='File size in bytes')),
                ('duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('is_compressed', models.BooleanField(default=False, help_text='Whether ffmpeg-audio compression has run (opt-in submodule)')),
                ('refs', models.JSONField(blank=True, default=list, help_text='List of references: service/entity_type/entity_id')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_audio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audio',
                'db_table': 'cdn_audio',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_hash'], name='cdn_audio_file_ha_ba1b30_idx'), models.Index(fields=['created_at'], name='cdn_audio_created_e8c499_idx')],
            },
        ),
    ]
