# Generated by Django 6.0.8 on 2026-08-14 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0004_alter_image_type_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='image',
            name='cdn_image_hash_type_unique',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_hash',
            field=models.CharField(db_index=True, help_text='SHA-256 hash of the original file', max_length=64),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_hash',
            field=models.CharField(db_index=True, help_text='SHA-256 hash of the original file', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('uploaded_by__isnull', False)), fields=('file_hash', 'uploaded_by'), name='cdn_file_hash_owner_unique'),
        ),
        migrations.AddConstraint(
            model_name='file',
            constraint=models.UniqueConstraint(condition=models.Q(('uploaded_by__isnull', True)), fields=('file_hash',), name='cdn_file_hash_service_unique'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(condition=models.Q(('uploaded_by__isnull', False)), fields=('file_hash', 'type', 'uploaded_by'), name='cdn_image_hash_type_owner_unique'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(condition=models.Q(('uploaded_by__isnull', True)), fields=('file_hash', 'type'), name='cdn_image_hash_type_service_unique'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(condition=models.Q(('uploaded_by__isnull', False)), fields=('file_hash', 'uploaded_by'), name='cdn_video_hash_owner_unique'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(condition=models.Q(('uploaded_by__isnull', True)), fields=('file_hash',), name='cdn_video_hash_service_unique'),
        ),
    ]
