# Generated by Django 6.0.7 on 2026-08-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0005_per_owner_media_ownership'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='variants_ready_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When variant generation completed; null while pending', null=True),
        ),
    ]
