# Generated by Django 6.0.7 on 2026-09-02 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0007_media_render_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='unreferenced_since',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text='When this object last became zero-ref; NULL while anything references it. The sweep TTL counts from here.', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='unreferenced_since',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text='When this object last became zero-ref; NULL while anything references it. The sweep TTL counts from here.', null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='unreferenced_since',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text='When this object last became zero-ref; NULL while anything references it. The sweep TTL counts from here.', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='unreferenced_since',
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, help_text='When this object last became zero-ref; NULL while anything references it. The sweep TTL counts from here.', null=True),
        ),
    ]
